name: 'strava_analytics'
version: '1.0.0'
config-version: 2
profile: 'strava_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  strava_analytics:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
    metrics:
      +materialized: table
      +schema: metrics
